on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/public/uploads'
name: 🚀 Deploying to sip and dip
jobs:
  web-deploy:
    name: Deploying...
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2.3.2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.remotemining.net
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Clear Route
        run: php artisan route:cache
      - name: Optimize file
        run: php artisan optimize:clear
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        